language: rust
dist: trusty
sudo: false
rust:
  # - 1.12.0
  # - stable
  # - beta
  - nightly
script: ci/script.sh
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - wget
      - clang-3.6
      - cmake
      - python
      - python-virtualenv
after_success: ci/after_success.sh
env:
  global:
    secure: "DjM9j+3vsQtfVxwNs1GTp/iq/H+hgA6RoSN4Iyodqdfet0zbbyHGdJpWis0DjQhfOCKatfo5E55Yow8+RwytzxeRAk4IuO8KW/NBz20nAjfJwSXlqqvS3jaJ0cmsfhViJK6YoEL7Sl4WrJWlvVJQwCkLX4dcF2R2rWRw1tudIls="
notifications:
  email:
    on_success: never
